"ui.background" = { bg = "p2" }
"ui.background.separator" = { fg = "p7" }

"ui.cursor" = { fg = "p2", bg = "p11" }
"ui.cursor.insert" = { fg = "p2", bg = "main" }
"ui.cursor.select" = { fg = "p2", bg = "p12" }
"ui.cursor.match" = { fg = "p12", modifiers = ["bold"] }
"ui.cursor.primary" = { fg = "p2", bg = "p11", modifiers = ["bold"] }
"ui.cursor.primary.insert" = { fg = "p2", bg = "main", modifiers = ["bold"] }
"ui.cursor.primary.select" = { fg = "p2", bg = "p12", modifiers = ["bold"] }

"ui.linenr" = { fg = "p7" }
"ui.linenr.selected" = { fg = "p11" }

"ui.statusline" = { fg = "p11", bg = "p4" }
"ui.statusline.inactive" = { fg = "p11", bg = "p2" }
"ui.statusline.normal" = { fg = "p2", bg = "p11" }
"ui.statusline.insert" = { fg = "p2", bg = "main" }
"ui.statusline.select" = { fg = "p2", bg = "p12" }
"ui.statusline.separator" = { fg = "p7" }

"ui.bufferline" = { fg = "p11", bg = "p4" }
"ui.bufferline.active" = { fg = "p2", bg = "p11" }

"ui.popup" = { fg = "p12", bg = "p4" }
"ui.popup.info" = { fg = "p12", bg = "p2" }

"ui.picker.header.column" = { underline.style = "line" }

"ui.window" = { fg = "p7" }

"ui.help" = { fg = "p12", bg = "p2" }

"ui.text" = { fg = "p11" }
"ui.text.focus" = { fg = "p12", modifiers = ["bold"] }
"ui.text.info" = { fg = "p12", bg = "p2" }

"ui.virtual" = { fg = "p5" }
"ui.virtual.ruler" = { bg = "p3" }
"ui.virtual.whitespace" = { fg = "p6" }
"ui.virtual.inlay-hint" = { fg = "p7", underline.style = "dotted" }
"ui.virtual.jump-label" = { fg = "p12", modifiers = [
  "bold",
], underline = { style = "curl", color = "info" } }

"ui.menu" = { fg = "p11", bg = "p4" }
"ui.menu.selected" = { fg = "p12", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "p8", bg = "p4" }

"ui.selection" = { bg = "p4" }
"ui.selection.primary" = { bg = "p5" }

"ui.cursorline.primary" = { bg = "p1" }
"ui.cursorcolumn.primary" = { bg = "p3" }

warning = { fg = "warning", modifiers = ["bold"] }
error = { fg = "error", modifiers = ["bold"] }
info = { fg = "info", modifiers = ["bold"] }
hint = { fg = "info", modifiers = ["bold"] }

"diagnostic.hint" = { fg = "info", modifiers = ["bold"] }
"diagnostic.info" = { fg = "info", modifiers = ["bold"] }
"diagnostic.warning" = { fg = "warning", modifiers = ["bold"] }
"diagnostic.error" = { fg = "error", modifiers = ["bold"] }

attribute = { fg = "p10" }
type = { fg = "p11" }
constructor = { fg = "p12" }
constant = { fg = "p12" }
string = { fg = "accent" }
comment = { fg = "info" }
variable = { fg = "p12" }
label = { fg = "p12" }
punctuation = { fg = "p10" }
keyword = { fg = "main" }
operator = { fg = "main" }
function = { fg = "p12" }
tag = { fg = "main" }
namespace = { fg = "p12" }
diff = { fg = "p10" }

"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.heading" = { fg = "p12", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "p8" }
"markup.list" = { fg = "p8" }
"markup.link.url" = { underline.style = "line" }
"markup.link.label" = { underline.style = "dotted" }
"markup.quote" = { fg = "p10" }


[palette]
error    = "#db162f"  # fire engine red
warning  = "#f0b7b3"  # melon
info     = "#56e39f"  # aquamarine
#            gray
p1       = "#191919"
p2       = "#202020"
p3       = "#282828"
p4       = "#2e2e2e"
p5       = "#343434"
p6       = "#3c3c3c"
p7       = "#494949"
p8       = "#616161"
p9       = "#6f6f6f"
p10      = "#7c7c7c"
p11      = "#b4b4b4"
p12      = "#eeeeee"
#            gold
main     = "#FFD702"
accent   = "#F9EBB7"
