# Author: Michael McClintock <michael.mcclintock@hey.com>
# License: MIT

# Yo - Themes for Helix inspired by Zenbones & Alabaster with Radix Colors.
# https://github.com/mrmcc3/yo-theme-helix

inherits = "yo"

[palette]

# grayDark. shift p1-p5 -> p2-p6
p2 = "#111111"
p3 = "#191919"
p4 = "#222222"
p5 = "#2a2a2a"
p6 = "#313131"
