# Author: Michael McClintock <michael.mcclintock@hey.com>
# License: MIT

# Yo - Themes for Helix inspired by Zenbones & Alabaster with Radix Colors.
# https://github.com/mrmcc3/yo-theme-helix

inherits = "yo_sand"

[palette]

# sandDark. shift p1-p5 -> p2-p6
p2 = "#111110"
p3 = "#191918"
p4 = "#222221"
p5 = "#2a2a28"
p6 = "#31312e"
