live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 18

[font.normal]
family = "RobotoMono Nerd Font"
style = "Medium"

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "Both"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 4
y = 4

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "E", mods = "Command", chars = "\u0002\"" },  # split tmux window vertically
  { key = "E", mods = "Command|Shift", chars = "\u0002%" },  # split tmux window horizontally
  { key = "F", mods = "Command|Shift", chars = "\u0002\u005b\u002f" },  # start tmux search mode
  { key = "K", mods = "Command", chars = "\u0002s" },  # open interactive tmux session client
  { key = "L", mods = "Command", chars = "\u0002L" },  # switch to the last tmux session
  { key = "S", mods = "Command", chars = "\u001b\u003a\u0077\u000a" },  # save vim buffer
  { key = "T", mods = "Command", chars = "\u0002c" },  # create a new tmux window
  { key = "W", mods = "Command", chars = "\u0002x" },  # kill the current pane
  { key = "Z", mods = "Command", chars = "\u0002z" },  # toggle zoom state of the current tmux pane
  { key = "Tab", mods = "Control", chars = "\u0002n" },  # switch to next tmux window
  { key = "`", mods = "Control", chars = "\u0002p" },  # switch to previous tmux window
  { key = "Comma", mods = "Command", chars = "\u0002," },  # rename the current tmux window
  { key = "LBracket", mods = "Command", chars = "\u000f" },  # navigate back in vim (ctrl+o)
  { key = "LBracket", mods = "Command|Shift", chars = "\u0002p" },  # switch to next tmux window
  { key = "RBracket", mods = "Command", chars = "\u0009" },  # navigate forward in vim (ctrl+i)
  { key = "RBracket", mods = "Command|Shift", chars = "\u0002n" },  # switch to previous tmux window
  { key = "Semicolon", mods = "Command", chars = "\u0002:" },  # enter the tmux command prompt
  { key = "Key1", mods = "Command", chars = "\u00021" },  # select tmux window 1
  { key = "Key2", mods = "Command", chars = "\u00022" },  #                ... 2
  { key = "Key3", mods = "Command", chars = "\u00023" },  #                ... 3
  { key = "Key4", mods = "Command", chars = "\u00024" },  #                ... 4
  { key = "Key5", mods = "Command", chars = "\u00025" },  #                ... 5
  { key = "Key6", mods = "Command", chars = "\u00026" },  #                ... 6
  { key = "Key7", mods = "Command", chars = "\u00027" },  #                ... 7
  { key = "Key8", mods = "Command", chars = "\u00028" },  #                ... 8
  { key = "Key9", mods = "Command", chars = "\u00029" },  #                ... 9
]
