theme = "gigagold"

[editor]
clipboard-provider = "pasteboard"
true-color = true
cursorline = true
color-modes = true
line-number = "relative"
rulers = [80]

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "total-line-numbers", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.file-picker]
hidden = false
git-ignore = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
tab = "→"
space = "·"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
A-w = 'move_next_sub_word_start'
A-b = 'move_prev_sub_word_start'
A-e = 'move_next_sub_word_end'

[keys.normal."space"]
A-f = "file_picker_in_current_buffer_directory"

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
A-w = 'extend_next_sub_word_start'
A-b = 'extend_prev_sub_word_start'
A-e = 'extend_next_sub_word_end'

[keys.select."space"]
A-f = "file_picker_in_current_buffer_directory"
