[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
diagnosticMode = "workspace"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.emmet-ls]
command = "emmet-ls"
args = [ "--stdio" ]


[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ "pyright", "ruff" ]

[[language]]
name = "rust"
auto-format = true
formatter = { command = "cargo fmt" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "clangd" ]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server", "emmet-ls" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server", "emmet-ls" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = [ "--parser", "json" ] }
auto-format = true

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true
